[package]
name = "noneed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "0.6"
anyhow = "1"
thiserror = "1"
rand = "0.8"

[dev-dependencies]
futures-lite = "1"
